version: '{build}-{branch}'
image: Visual Studio 2017

sskip_commits:
  files:
  - '**/*.md'

  build_script:
  - pwsh: dotnet build -c Release

  test_script:
  - pwsh: dotnet test ./tests/Prometheus.Client.MetricServer.NetCore.Tests -c Release --no-build

  after_test:
  - pwsh: .\pack.ps1

  artifacts:
  - path: '**\artifacts\nuget\*.nupkg'
    name: Nuget
  - path: '**\artifacts\myget\*.nupkg'
  name: Myget
  
deploy:
- provider: NuGet
  api_key:
    secure: vbPWVWUYJ4zSn7fQ621uITPR99Q2s+bx36nE97IUOFrjgjAkMSJ9KOoFTXTGPAl1
  on:
    appveyor_repo_tag: true
