version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- ps: .\build.ps1

test_script:
- ps: .\test.ps1

after_test:
- ps: .\pack.ps1

artifacts:
- path: '**\*.nupkg'
  name: All Nupkg
  
deploy:
- provider: NuGet
  api_key:
    secure: vukCl5k+S4fJtqeYNiB9ufy/NUCw+60cPcqnPoqvykBjSo8Ub8QtEfZNN9qvj5Jh
  on:
    appveyor_repo_tag: true